In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [22]:
#from google.colab import files
#uploaded = files.upload()
df = pd.read_csv('payment_fraud.csv')
df.head()

,accountAgeDays,numItems,localTime,paymentMethod,paymentMethodAgeDays,label
0,29,1,4.745402,paypal,28.204861,0
1,725,1,4.742303,storecredit,0.000000,0
2,845,1,4.921318,creditcard,0.000000,0
3,503,1,4.886641,creditcard,0.000000,0
4,2000,1,5.040929,creditcard,0.000000,0

In [23]:
df['paymentMethod'].unique()

array(['paypal', 'storecredit', 'creditcard'], dtype=object)

In [24]:
df_ch = df
df_ch['paymentMethod'] = df_ch['paymentMethod'].replace(['paypal','storecredit','creditcard'],[1,2,3])
df_ch.head()

,accountAgeDays,numItems,localTime,paymentMethod,paymentMethodAgeDays,label
0,29,1,4.745402,1,28.204861,0
1,725,1,4.742303,2,0.000000,0
2,845,1,4.921318,3,0.000000,0
3,503,1,4.886641,3,0.000000,0
4,2000,1,5.040929,3,0.000000,0

In [25]:
df_ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39221 entries, 0 to 39220
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   accountAgeDays        39221 non-null  int64
 1   numItems              39221 non-null  int64
 2   localTime             39221 non-null  float64
 3   paymentMethod         39221 non-null  int64
 4   paymentMethodAgeDays  39221 non-null  float64
 5   label                 39221 non-null  int64
dtypes: float64(2), int64(4)
memory usage: 1.8 MB

In [26]:
df_dr = df.drop(['paymentMethod'], axis=1)
df_dr.head()

   accountAgeDays  numItems  localTime  paymentMethodAgeDays  label
0              29         1   4.745402             28.204861      0
1             725         1   4.742303              0.000000      0
2             845         1   4.921318              0.000000      0
3             503         1   4.886641              0.000000      0
4            2000         1   5.040929              0.000000      0

In [42]:
# Split dataset up into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    df_dr.drop('label', axis=1), df_dr['label'],
    test_size=0.33, random_state=17)

In [43]:
clf = LogisticRegression().fit(X_train, y_train)

# Make predictions on test set
y_pred = clf.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred, y_test))

1.0

In [44]:
# Compare test set predictions with ground truth labels
print(confusion_matrix(y_test, y_pred))

[[12753     0]
 [    0   190]]

In [45]:
print(clf)

LogisticRegression()

In [36]:
# Split dataset up into train and test sets
X_train2, X_test2, y_train2, y_test2 = train_test_split(
    df_ch.drop('label', axis=1), df_ch['label'],
    test_size=0.33, random_state=17)

In [37]:
clf2 = LogisticRegression().fit(X_train2, y_train2)

# Make predictions on test set
y_pred2 = clf2.predict(X_test2)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred2, y_test2))

1.0

In [38]:
print(confusion_matrix(y_test2, y_pred2))

[[12753     0]
 [    0   190]]