In [2]:
pip install s2sphere

Collecting s2sphere
  Downloading s2sphere-0.2.5-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: future>=0.15 in c:\users\anugrah.rusdianto\anaconda3\lib\site-packages (from s2sphere) (0.18.2)
Installing collected packages: s2sphere
Successfully installed s2sphere-0.2.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import s2sphere

In [5]:
p1 = s2sphere.LatLng.from_degrees(-8.571423, 115.333109)
cell = s2sphere.CellId.from_lat_lng(p1)
cell11 = cell.parent(13)
c11id = str(cell11.id())
print(c11id)

3301723690386849792

In [25]:
df_shp = pd.read_excel('rawmerchantshp.xlsx', index = False)
df_shp.head()

,merchant_id_shp,merchant_name_shp,gps_latitude_shp,gps_longitude_shp,outlet_id_shp,outlet_name_shp
0,8212,Bakso Jawir (JWR),-6.15072,106.70270,8221,"JWR Ruko, Duta Indah"
1,8845,PRIMA FRESHMART 1,-6.14760,106.70244,9114,"PFM, KALIDERES JXDRES1"
2,478827,Domino's Pizza_,-6.14420,106.70634,479580,"Domino's, Pizza Citra 3"
3,15754,KFC,-6.15605,106.71623,17215,"KFC, DAAN MOGOT BARU"
4,40549,MCDONALDS,-6.15092,106.71446,82467,"McD, Mal Daan Mogot FC"

In [42]:
#generating s2id from lat long
#changing df format to list
lat = df_shp.gps_latitude_shp.values.tolist()
lon = df_shp.gps_longitude_shp.values.tolist()

s2id = [] 

cellId1 = []
cellId2 = []
cellId3 = []

for i in range(0,len(lat)):
    p1 = s2sphere.LatLng.from_degrees(lat[i], lon[i])
    cell = s2sphere.CellId.from_lat_lng(p1)
    cell11 = cell.parent(11)
    c11id = str(cell11.id())
    s2id.append(cell11.id())
    #print(cid)
    ##cid is a 19 digit number so python storing it as Object, not number
    ##So I am converting it into 3 numbers
    cellId1.append(int(c11id[:6]))
    cellId2.append(int(c11id[6:12]))
    cellId3.append(int(c11id[12:19]))
    
se = pd.Series(s2id)
#df = se.to_frame()
#df.info()
#df.head()
df_shp['s2id11'] = se.values

se = pd.Series(cellId1)
df_shp['s211id1'] = se.values

se = pd.Series(cellId2)
df_shp['s211id2'] = se.values

se = pd.Series(cellId3)
df_shp['s211id3'] = se.values

df_shp = df_shp.loc[:, ['merchant_id_shp','merchant_name_shp','gps_latitude_shp','gps_longitude_shp','outlet_id_shp','outlet_name_shp','s2id11','s211id1','s211id2','s211id3']]
df_shp.head()

,merchant_id_shp,merchant_name_shp,gps_latitude_shp,gps_longitude_shp,outlet_id_shp,outlet_name_shp,s2id11,s211id1,s211id2,s211id3
0,8212,Bakso Jawir (JWR),-6.15072,106.70270,8221,"JWR Ruko, Duta Indah",3344477152060899328,334447,715206,899328
1,8845,PRIMA FRESHMART 1,-6.14760,106.70244,9114,"PFM, KALIDERES JXDRES1",3344477152060899328,334447,715206,899328
2,478827,Domino's Pizza_,-6.14420,106.70634,479580,"Domino's, Pizza Citra 3",3344477152060899328,334447,715206,899328
3,15754,KFC,-6.15605,106.71623,17215,"KFC, DAAN MOGOT BARU",3344477152060899328,334447,715206,899328
4,40549,MCDONALDS,-6.15092,106.71446,82467,"McD, Mal Daan Mogot FC",3344477152060899328,334447,715206,899328

In [30]:
df_comp = pd.read_excel('rawmerchantcomp.xlsx', index = False)
df_comp.head()

,merchant_id_comp,merchant_name_comp,latitude_comp,longitude_comp
0,542538094,"Bakso Jawir (JWR), Ruko Duta Indah",-6.147444,106.702417
1,543399556,"Prima Freshmart, Kalideres",-6.147619,106.702415
2,542531234,"Domino's Pizza, Citra Garden 2",-6.144993,106.706230
3,542675827,"KFC, Daan Mogot Baru",-6.153440,106.713879
4,542530624,"McDonald's, Mal Daan Mogot",-6.151077,106.714432

In [31]:
#generating s2id from lat long
#changing df format to list
lat = df_comp.latitude_comp.values.tolist()
lon = df_comp.longitude_comp.values.tolist()

s2id = [] 

cellId1 = []
cellId2 = []
cellId3 = []

for i in range(0,len(lat)):
    p1 = s2sphere.LatLng.from_degrees(lat[i], lon[i])
    cell = s2sphere.CellId.from_lat_lng(p1)
    cell11 = cell.parent(11)
    c11id = str(cell11.id())
    s2id.append(cell11.id())
    #print(cid)
    ##cid is a 19 digit number so python storing it as Object, not number
    ##So I am converting it into 3 numbers
    cellId1.append(int(c11id[:6]))
    cellId2.append(int(c11id[6:12]))
    cellId3.append(int(c11id[12:19]))

se = pd.Series(s2id)
#df = se.to_frame()
#df.info()
#df.head()
df_comp['s2id11'] = se.values

se = pd.Series(cellId1)
df_comp['s211id1'] = se.values

se = pd.Series(cellId2)
df_comp['s211id2'] = se.values

se = pd.Series(cellId3)
df_comp['s211id3'] = se.values

df_comp = df_comp.loc[:, ['merchant_id_comp','merchant_name_comp','latitude_comp','longitude_comp','s2id11','s211id1','s211id2','s211id3']]
df_comp.head()

,merchant_id_comp,merchant_name_comp,latitude_comp,longitude_comp,s2id11,s211id1,s211id2,s211id3
0,542538094,"Bakso Jawir (JWR), Ruko Duta Indah",-6.147444,106.702417,3344477152060899328,334447,715206,899328
1,543399556,"Prima Freshmart, Kalideres",-6.147619,106.702415,3344477152060899328,334447,715206,899328
2,542531234,"Domino's Pizza, Citra Garden 2",-6.144993,106.706230,3344477152060899328,334447,715206,899328
3,542675827,"KFC, Daan Mogot Baru",-6.153440,106.713879,3344477152060899328,334447,715206,899328
4,542530624,"McDonald's, Mal Daan Mogot",-6.151077,106.714432,3344477152060899328,334447,715206,899328

In [33]:
df_inner = pd.merge(df_shp, df_comp, left_on=['s2id11'],right_on=['s2id11'],how='inner',suffixes=('_shp','_comp'))
df_inner.head()

,merchant_id_shp,merchant_name_shp,gps_latitude_shp,gps_longitude_shp,outlet_id_shp,outlet_name_shp,s2id11,s211id1_shp,s211id2_shp,s211id3_shp,merchant_id_comp,merchant_name_comp,latitude_comp,longitude_comp,s211id1_comp,s211id2_comp,s211id3_comp
0,8212,Bakso Jawir (JWR),-6.15072,106.7027,8221,"JWR Ruko, Duta Indah",3344477152060899328,334447,715206,899328,542538094,"Bakso Jawir (JWR), Ruko Duta Indah",-6.147444,106.702417,334447,715206,899328
1,8212,Bakso Jawir (JWR),-6.15072,106.7027,8221,"JWR Ruko, Duta Indah",3344477152060899328,334447,715206,899328,543399556,"Prima Freshmart, Kalideres",-6.147619,106.702415,334447,715206,899328
2,8212,Bakso Jawir (JWR),-6.15072,106.7027,8221,"JWR Ruko, Duta Indah",3344477152060899328,334447,715206,899328,542531234,"Domino's Pizza, Citra Garden 2",-6.144993,106.706230,334447,715206,899328
3,8212,Bakso Jawir (JWR),-6.15072,106.7027,8221,"JWR Ruko, Duta Indah",3344477152060899328,334447,715206,899328,542675827,"KFC, Daan Mogot Baru",-6.153440,106.713879,334447,715206,899328
4,8212,Bakso Jawir (JWR),-6.15072,106.7027,8221,"JWR Ruko, Duta Indah",3344477152060899328,334447,715206,899328,542530624,"McDonald's, Mal Daan Mogot",-6.151077,106.714432,334447,715206,899328

In [34]:
print(df_inner)

    merchant_id_shp   merchant_name_shp  gps_latitude_shp  gps_longitude_shp  \
0              8212   Bakso Jawir (JWR)          -6.15072          106.70270
1              8212   Bakso Jawir (JWR)          -6.15072          106.70270
2              8212   Bakso Jawir (JWR)          -6.15072          106.70270
3              8212   Bakso Jawir (JWR)          -6.15072          106.70270
4              8212   Bakso Jawir (JWR)          -6.15072          106.70270
5              8212   Bakso Jawir (JWR)          -6.15072          106.70270
6              8212   Bakso Jawir (JWR)          -6.15072          106.70270
7              8845   PRIMA FRESHMART 1          -6.14760          106.70244
8              8845   PRIMA FRESHMART 1          -6.14760          106.70244
9              8845   PRIMA FRESHMART 1          -6.14760          106.70244
10             8845   PRIMA FRESHMART 1          -6.14760          106.70244
11             8845   PRIMA FRESHMART 1          -6.14760          106.70244
12             8845   PRIMA FRESHMART 1          -6.14760          106.70244
13             8845   PRIMA FRESHMART 1          -6.14760          106.70244
14           478827     Domino's Pizza_          -6.14420          106.70634
15           478827     Domino's Pizza_          -6.14420          106.70634
16           478827     Domino's Pizza_          -6.14420          106.70634
17           478827     Domino's Pizza_          -6.14420          106.70634
18           478827     Domino's Pizza_          -6.14420          106.70634
19           478827     Domino's Pizza_          -6.14420          106.70634
20           478827     Domino's Pizza_          -6.14420          106.70634
21            15754                 KFC          -6.15605          106.71623
22            15754                 KFC          -6.15605          106.71623
23            15754                 KFC          -6.15605          106.71623
24            15754                 KFC          -6.15605          106.71623
25            15754                 KFC          -6.15605          106.71623
26            15754                 KFC          -6.15605          106.71623
27            15754                 KFC          -6.15605          106.71623
28            40549           MCDONALDS          -6.15092          106.71446
29            40549           MCDONALDS          -6.15092          106.71446
30            40549           MCDONALDS          -6.15092          106.71446
31            40549           MCDONALDS          -6.15092          106.71446
32            40549           MCDONALDS          -6.15092          106.71446
33            40549           MCDONALDS          -6.15092          106.71446
34            40549           MCDONALDS          -6.15092          106.71446
35             5284            Kopi Soe          -6.14682          106.70845
36             5284            Kopi Soe          -6.14682          106.70845
37             5284            Kopi Soe          -6.14682          106.70845
38             5284            Kopi Soe          -6.14682          106.70845
39             5284            Kopi Soe          -6.14682          106.70845
40             5284            Kopi Soe          -6.14682          106.70845
41             5284            Kopi Soe          -6.14682          106.70845
42            32120             CHATIME          -6.15179          106.71361
43            32120             CHATIME          -6.15179          106.71361
44            32120             CHATIME          -6.15179          106.71361
45            32120             CHATIME          -6.15179          106.71361
46            32120             CHATIME          -6.15179          106.71361
47            32120             CHATIME          -6.15179          106.71361
48            32120             CHATIME          -6.15179          106.71361
49           118743            Alfamart          -7.99146          112.68444
50            36096        Mie Dua Rasa          -7.73868          109.00742
51           124512  Ayam Rasa Bu Darmi          -7.95146          112.65444

    outlet_id_shp             outlet_name_shp               s2id11  \
0            8221        JWR Ruko, Duta Indah  3344477152060899328
1            8221        JWR Ruko, Duta Indah  3344477152060899328
2            8221        JWR Ruko, Duta Indah  3344477152060899328
3            8221        JWR Ruko, Duta Indah  3344477152060899328
4            8221        JWR Ruko, Duta Indah  3344477152060899328
5            8221        JWR Ruko, Duta Indah  3344477152060899328
6            8221        JWR Ruko, Duta Indah  3344477152060899328
7            9114      PFM, KALIDERES JXDRES1  3344477152060899328
8            9114      PFM, KALIDERES JXDRES1  3344477152060899328
9            9114      PFM, KALIDERES JXDRES1  3344477152060899328
10           9114      PFM, KALIDERES JXDRES1  3344477152060899328
11           9114      PFM, KALIDERES JXDRES1  3344477152060899328
12           9114      PFM, KALIDERES JXDRES1  3344477152060899328
13           9114      PFM, KALIDERES JXDRES1  3344477152060899328
14         479580     Domino's, Pizza Citra 3  3344477152060899328
15         479580     Domino's, Pizza Citra 3  3344477152060899328
16         479580     Domino's, Pizza Citra 3  3344477152060899328
17         479580     Domino's, Pizza Citra 3  3344477152060899328
18         479580     Domino's, Pizza Citra 3  3344477152060899328
19         479580     Domino's, Pizza Citra 3  3344477152060899328
20         479580     Domino's, Pizza Citra 3  3344477152060899328
21          17215        KFC, DAAN MOGOT BARU  3344477152060899328
22          17215        KFC, DAAN MOGOT BARU  3344477152060899328
23          17215        KFC, DAAN MOGOT BARU  3344477152060899328
24          17215        KFC, DAAN MOGOT BARU  3344477152060899328
25          17215        KFC, DAAN MOGOT BARU  3344477152060899328
26          17215        KFC, DAAN MOGOT BARU  3344477152060899328
27          17215        KFC, DAAN MOGOT BARU  3344477152060899328
28          82467     McD, Mal Daan Mogot FC   3344477152060899328
29          82467     McD, Mal Daan Mogot FC   3344477152060899328
30          82467     McD, Mal Daan Mogot FC   3344477152060899328
31          82467     McD, Mal Daan Mogot FC   3344477152060899328
32          82467     McD, Mal Daan Mogot FC   3344477152060899328
33          82467     McD, Mal Daan Mogot FC   3344477152060899328
34          82467     McD, Mal Daan Mogot FC   3344477152060899328
35           5288         Kopi Soe, GoWork CP  3344477152060899328
36           5288         Kopi Soe, GoWork CP  3344477152060899328
37           5288         Kopi Soe, GoWork CP  3344477152060899328
38           5288         Kopi Soe, GoWork CP  3344477152060899328
39           5288         Kopi Soe, GoWork CP  3344477152060899328
40           5288         Kopi Soe, GoWork CP  3344477152060899328
41           5288         Kopi Soe, GoWork CP  3344477152060899328
42         115076  CHATIME, MATAHARI DAAN MGT  3344477152060899328
43         115076  CHATIME, MATAHARI DAAN MGT  3344477152060899328
44         115076  CHATIME, MATAHARI DAAN MGT  3344477152060899328
45         115076  CHATIME, MATAHARI DAAN MGT  3344477152060899328
46         115076  CHATIME, MATAHARI DAAN MGT  3344477152060899328
47         115076  CHATIME, MATAHARI DAAN MGT  3344477152060899328
48         115076  CHATIME, MATAHARI DAAN MGT  3344477152060899328
49         159902   ALFAMART, NGANTANG MALANG  3302872181821669376
50          36434                Mie Dua Rasa  3343098364479668224
51          67890              ARBD, Surabaya  3302873281333297152

    s211id1_shp  s211id2_shp  s211id3_shp  merchant_id_comp  \
0        334447       715206       899328         542538094
1        334447       715206       899328         543399556
2        334447       715206       899328         542531234
3        334447       715206       899328         542675827
4        334447       715206       899328         542530624
5        334447       715206       899328         543119305
6        334447       715206       899328         543283041
7        334447       715206       899328         542538094
8        334447       715206       899328         543399556
9        334447       715206       899328         542531234
10       334447       715206       899328         542675827
11       334447       715206       899328         542530624
12       334447       715206       899328         543119305
13       334447       715206       899328         543283041
14       334447       715206       899328         542538094
15       334447       715206       899328         543399556
16       334447       715206       899328         542531234
17       334447       715206       899328         542675827
18       334447       715206       899328         542530624
19       334447       715206       899328         543119305
20       334447       715206       899328         543283041
21       334447       715206       899328         542538094
22       334447       715206       899328         543399556
23       334447       715206       899328         542531234
24       334447       715206       899328         542675827
25       334447       715206       899328         542530624
26       334447       715206       899328         543119305
27       334447       715206       899328         543283041
28       334447       715206       899328         542538094
29       334447       715206       899328         543399556
30       334447       715206       899328         542531234
31       334447       715206       899328         542675827
32       334447       715206       899328         542530624
33       334447       715206       899328         543119305
34       334447       715206       899328         543283041
35       334447       715206       899328         542538094
36       334447       715206       899328         543399556
37       334447       715206       899328         542531234
38       334447       715206       899328         542675827
39       334447       715206       899328         542530624
40       334447       715206       899328         543119305
41       334447       715206       899328         543283041
42       334447       715206       899328         542538094
43       334447       715206       899328         543399556
44       334447       715206       899328         542531234
45       334447       715206       899328         542675827
46       334447       715206       899328         542530624
47       334447       715206       899328         543119305
48       334447       715206       899328         543283041
49       330287       218182      1669376         543342911
50       334309       836447      9668224         542630974
51       330287       328133      3297152         543642912

                    merchant_name_comp  latitude_comp  longitude_comp  \
0   Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
1           Prima Freshmart, Kalideres      -6.147619      106.702415
2       Domino's Pizza, Citra Garden 2      -6.144993      106.706230
3                 KFC, Daan Mogot Baru      -6.153440      106.713879
4           McDonald's, Mal Daan Mogot      -6.151077      106.714432
5             Kopi Kenangan, GoWork CP      -6.148143      106.708149
6    Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
7   Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
8           Prima Freshmart, Kalideres      -6.147619      106.702415
9       Domino's Pizza, Citra Garden 2      -6.144993      106.706230
10                KFC, Daan Mogot Baru      -6.153440      106.713879
11          McDonald's, Mal Daan Mogot      -6.151077      106.714432
12            Kopi Kenangan, GoWork CP      -6.148143      106.708149
13   Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
14  Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
15          Prima Freshmart, Kalideres      -6.147619      106.702415
16      Domino's Pizza, Citra Garden 2      -6.144993      106.706230
17                KFC, Daan Mogot Baru      -6.153440      106.713879
18          McDonald's, Mal Daan Mogot      -6.151077      106.714432
19            Kopi Kenangan, GoWork CP      -6.148143      106.708149
20   Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
21  Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
22          Prima Freshmart, Kalideres      -6.147619      106.702415
23      Domino's Pizza, Citra Garden 2      -6.144993      106.706230
24                KFC, Daan Mogot Baru      -6.153440      106.713879
25          McDonald's, Mal Daan Mogot      -6.151077      106.714432
26            Kopi Kenangan, GoWork CP      -6.148143      106.708149
27   Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
28  Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
29          Prima Freshmart, Kalideres      -6.147619      106.702415
30      Domino's Pizza, Citra Garden 2      -6.144993      106.706230
31                KFC, Daan Mogot Baru      -6.153440      106.713879
32          McDonald's, Mal Daan Mogot      -6.151077      106.714432
33            Kopi Kenangan, GoWork CP      -6.148143      106.708149
34   Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
35  Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
36          Prima Freshmart, Kalideres      -6.147619      106.702415
37      Domino's Pizza, Citra Garden 2      -6.144993      106.706230
38                KFC, Daan Mogot Baru      -6.153440      106.713879
39          McDonald's, Mal Daan Mogot      -6.151077      106.714432
40            Kopi Kenangan, GoWork CP      -6.148143      106.708149
41   Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
42  Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
43          Prima Freshmart, Kalideres      -6.147619      106.702415
44      Domino's Pizza, Citra Garden 2      -6.144993      106.706230
45                KFC, Daan Mogot Baru      -6.153440      106.713879
46          McDonald's, Mal Daan Mogot      -6.151077      106.714432
47            Kopi Kenangan, GoWork CP      -6.148143      106.708149
48   Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
49       Halal Mart HNI, Kedungkandang      -7.987778      112.676896
50                          Mie 2 Rasa      -7.737617      109.007828
51                  Bu Darmi Ayam Rasa      -7.951460      112.654440

    s211id1_comp  s211id2_comp  s211id3_comp
0         334447        715206        899328
1         334447        715206        899328
2         334447        715206        899328
3         334447        715206        899328
4         334447        715206        899328
5         334447        715206        899328
6         334447        715206        899328
7         334447        715206        899328
8         334447        715206        899328
9         334447        715206        899328
10        334447        715206        899328
11        334447        715206        899328
12        334447        715206        899328
13        334447        715206        899328
14        334447        715206        899328
15        334447        715206        899328
16        334447        715206        899328
17        334447        715206        899328
18        334447        715206        899328
19        334447        715206        899328
20        334447        715206        899328
21        334447        715206        899328
22        334447        715206        899328
23        334447        715206        899328
24        334447        715206        899328
25        334447        715206        899328
26        334447        715206        899328
27        334447        715206        899328
28        334447        715206        899328
29        334447        715206        899328
30        334447        715206        899328
31        334447        715206        899328
32        334447        715206        899328
33        334447        715206        899328
34        334447        715206        899328
35        334447        715206        899328
36        334447        715206        899328
37        334447        715206        899328
38        334447        715206        899328
39        334447        715206        899328
40        334447        715206        899328
41        334447        715206        899328
42        334447        715206        899328
43        334447        715206        899328
44        334447        715206        899328
45        334447        715206        899328
46        334447        715206        899328
47        334447        715206        899328
48        334447        715206        899328
49        330287        218182       1669376
50        334309        836447       9668224
51        330287        328133       3297152

In [35]:
#generating s2id from lat long
#changing df format to list
lat = df_shp.gps_latitude_shp.values.tolist()
lon = df_shp.gps_longitude_shp.values.tolist()

s2id = [] 

cellId1 = []
cellId2 = []
cellId3 = []

for i in range(0,len(lat)):
    p1 = s2sphere.LatLng.from_degrees(lat[i], lon[i])
    cell = s2sphere.CellId.from_lat_lng(p1)
    cell11 = cell.parent(13)
    c11id = str(cell11.id())
    s2id.append(cell11.id())
    #print(cid)
    ##cid is a 19 digit number so python storing it as Object, not number
    ##So I am converting it into 3 numbers
    cellId1.append(int(c11id[:6]))
    cellId2.append(int(c11id[6:12]))
    cellId3.append(int(c11id[12:19]))

se = pd.Series(s2id)
#df = se.to_frame()
#df.info()
#df.head()
df_shp['s2id13'] = se.values

se = pd.Series(cellId1)
df_shp['s213id1'] = se.values

se = pd.Series(cellId2)
df_shp['s213id2'] = se.values

se = pd.Series(cellId3)
df_shp['s213id3'] = se.values

df_shp = df_shp.loc[:, ['merchant_id_shp','merchant_name_shp','gps_latitude_shp','gps_longitude_shp','outlet_id_shp','outlet_name_shp','s2id13','s213id1','s213id2','s213id3']]
df_shp.head()

,merchant_id_shp,merchant_name_shp,gps_latitude_shp,gps_longitude_shp,outlet_id_shp,outlet_name_shp,s2id13,s213id1,s213id2,s213id3
0,8212,Bakso Jawir (JWR),-6.15072,106.70270,8221,"JWR Ruko, Duta Indah",3344476963082338304,334447,696308,2338304
1,8845,PRIMA FRESHMART 1,-6.14760,106.70244,9114,"PFM, KALIDERES JXDRES1",3344476928722599936,334447,692872,2599936
2,478827,Domino's Pizza_,-6.14420,106.70634,479580,"Domino's, Pizza Citra 3",3344476928722599936,334447,692872,2599936
3,15754,KFC,-6.15605,106.71623,17215,"KFC, DAAN MOGOT BARU",3344476997442076672,334447,699744,2076672
4,40549,MCDONALDS,-6.15092,106.71446,82467,"McD, Mal Daan Mogot FC",3344476997442076672,334447,699744,2076672

In [36]:
#generating s2id from lat long
#changing df format to list
lat = df_comp.latitude_comp.values.tolist()
lon = df_comp.longitude_comp.values.tolist()

s2id = [] 

cellId1 = []
cellId2 = []
cellId3 = []

for i in range(0,len(lat)):
    p1 = s2sphere.LatLng.from_degrees(lat[i], lon[i])
    cell = s2sphere.CellId.from_lat_lng(p1)
    cell11 = cell.parent(13)
    c11id = str(cell11.id())
    s2id.append(cell11.id())
    #print(cid)
    ##cid is a 19 digit number so python storing it as Object, not number
    ##So I am converting it into 3 numbers
    cellId1.append(int(c11id[:6]))
    cellId2.append(int(c11id[6:12]))
    cellId3.append(int(c11id[12:19]))

se = pd.Series(s2id)
#df = se.to_frame()
#df.info()
#df.head()
df_comp['s2id13'] = se.values

se = pd.Series(cellId1)
df_comp['s213id1'] = se.values

se = pd.Series(cellId2)
df_comp['s213id2'] = se.values

se = pd.Series(cellId3)
df_comp['s213id3'] = se.values

df_comp = df_comp.loc[:, ['merchant_id_comp','merchant_name_comp','latitude_comp','longitude_comp','s2id13','s213id1','s213id2','s213id3']]
df_comp.head()

,merchant_id_comp,merchant_name_comp,latitude_comp,longitude_comp,s2id13,s213id1,s213id2,s213id3
0,542538094,"Bakso Jawir (JWR), Ruko Duta Indah",-6.147444,106.702417,3344476928722599936,334447,692872,2599936
1,543399556,"Prima Freshmart, Kalideres",-6.147619,106.702415,3344476928722599936,334447,692872,2599936
2,542531234,"Domino's Pizza, Citra Garden 2",-6.144993,106.706230,3344476928722599936,334447,692872,2599936
3,542675827,"KFC, Daan Mogot Baru",-6.153440,106.713879,3344476997442076672,334447,699744,2076672
4,542530624,"McDonald's, Mal Daan Mogot",-6.151077,106.714432,3344476997442076672,334447,699744,2076672

In [37]:
df_inner2 = pd.merge(df_shp, df_comp, left_on=['s2id13'],right_on=['s2id13'],how='inner',suffixes=('_shp','_comp'))
df_inner2.head()

,merchant_id_shp,merchant_name_shp,gps_latitude_shp,gps_longitude_shp,outlet_id_shp,outlet_name_shp,s2id13,s213id1_shp,s213id2_shp,s213id3_shp,merchant_id_comp,merchant_name_comp,latitude_comp,longitude_comp,s213id1_comp,s213id2_comp,s213id3_comp
0,8845,PRIMA FRESHMART 1,-6.1476,106.70244,9114,"PFM, KALIDERES JXDRES1",3344476928722599936,334447,692872,2599936,542538094,"Bakso Jawir (JWR), Ruko Duta Indah",-6.147444,106.702417,334447,692872,2599936
1,8845,PRIMA FRESHMART 1,-6.1476,106.70244,9114,"PFM, KALIDERES JXDRES1",3344476928722599936,334447,692872,2599936,543399556,"Prima Freshmart, Kalideres",-6.147619,106.702415,334447,692872,2599936
2,8845,PRIMA FRESHMART 1,-6.1476,106.70244,9114,"PFM, KALIDERES JXDRES1",3344476928722599936,334447,692872,2599936,542531234,"Domino's Pizza, Citra Garden 2",-6.144993,106.706230,334447,692872,2599936
3,8845,PRIMA FRESHMART 1,-6.1476,106.70244,9114,"PFM, KALIDERES JXDRES1",3344476928722599936,334447,692872,2599936,543119305,"Kopi Kenangan, GoWork CP",-6.148143,106.708149,334447,692872,2599936
4,478827,Domino's Pizza_,-6.1442,106.70634,479580,"Domino's, Pizza Citra 3",3344476928722599936,334447,692872,2599936,542538094,"Bakso Jawir (JWR), Ruko Duta Indah",-6.147444,106.702417,334447,692872,2599936

In [38]:
print(df_inner2)

    merchant_id_shp   merchant_name_shp  gps_latitude_shp  gps_longitude_shp  \
0              8845   PRIMA FRESHMART 1          -6.14760          106.70244
1              8845   PRIMA FRESHMART 1          -6.14760          106.70244
2              8845   PRIMA FRESHMART 1          -6.14760          106.70244
3              8845   PRIMA FRESHMART 1          -6.14760          106.70244
4            478827     Domino's Pizza_          -6.14420          106.70634
5            478827     Domino's Pizza_          -6.14420          106.70634
6            478827     Domino's Pizza_          -6.14420          106.70634
7            478827     Domino's Pizza_          -6.14420          106.70634
8              5284            Kopi Soe          -6.14682          106.70845
9              5284            Kopi Soe          -6.14682          106.70845
10             5284            Kopi Soe          -6.14682          106.70845
11             5284            Kopi Soe          -6.14682          106.70845
12            15754                 KFC          -6.15605          106.71623
13            15754                 KFC          -6.15605          106.71623
14            15754                 KFC          -6.15605          106.71623
15            40549           MCDONALDS          -6.15092          106.71446
16            40549           MCDONALDS          -6.15092          106.71446
17            40549           MCDONALDS          -6.15092          106.71446
18            32120             CHATIME          -6.15179          106.71361
19            32120             CHATIME          -6.15179          106.71361
20            32120             CHATIME          -6.15179          106.71361
21            36096        Mie Dua Rasa          -7.73868          109.00742
22           124512  Ayam Rasa Bu Darmi          -7.95146          112.65444

    outlet_id_shp             outlet_name_shp               s2id13  \
0            9114      PFM, KALIDERES JXDRES1  3344476928722599936
1            9114      PFM, KALIDERES JXDRES1  3344476928722599936
2            9114      PFM, KALIDERES JXDRES1  3344476928722599936
3            9114      PFM, KALIDERES JXDRES1  3344476928722599936
4          479580     Domino's, Pizza Citra 3  3344476928722599936
5          479580     Domino's, Pizza Citra 3  3344476928722599936
6          479580     Domino's, Pizza Citra 3  3344476928722599936
7          479580     Domino's, Pizza Citra 3  3344476928722599936
8            5288         Kopi Soe, GoWork CP  3344476928722599936
9            5288         Kopi Soe, GoWork CP  3344476928722599936
10           5288         Kopi Soe, GoWork CP  3344476928722599936
11           5288         Kopi Soe, GoWork CP  3344476928722599936
12          17215        KFC, DAAN MOGOT BARU  3344476997442076672
13          17215        KFC, DAAN MOGOT BARU  3344476997442076672
14          17215        KFC, DAAN MOGOT BARU  3344476997442076672
15          82467     McD, Mal Daan Mogot FC   3344476997442076672
16          82467     McD, Mal Daan Mogot FC   3344476997442076672
17          82467     McD, Mal Daan Mogot FC   3344476997442076672
18         115076  CHATIME, MATAHARI DAAN MGT  3344476997442076672
19         115076  CHATIME, MATAHARI DAAN MGT  3344476997442076672
20         115076  CHATIME, MATAHARI DAAN MGT  3344476997442076672
21          36434                Mie Dua Rasa  3343098622177705984
22          67890              ARBD, Surabaya  3302873229793689600

    s213id1_shp  s213id2_shp  s213id3_shp  merchant_id_comp  \
0        334447       692872      2599936         542538094
1        334447       692872      2599936         543399556
2        334447       692872      2599936         542531234
3        334447       692872      2599936         543119305
4        334447       692872      2599936         542538094
5        334447       692872      2599936         543399556
6        334447       692872      2599936         542531234
7        334447       692872      2599936         543119305
8        334447       692872      2599936         542538094
9        334447       692872      2599936         543399556
10       334447       692872      2599936         542531234
11       334447       692872      2599936         543119305
12       334447       699744      2076672         542675827
13       334447       699744      2076672         542530624
14       334447       699744      2076672         543283041
15       334447       699744      2076672         542675827
16       334447       699744      2076672         542530624
17       334447       699744      2076672         543283041
18       334447       699744      2076672         542675827
19       334447       699744      2076672         542530624
20       334447       699744      2076672         543283041
21       334309       862217      7705984         542630974
22       330287       322979      3689600         543642912

                    merchant_name_comp  latitude_comp  longitude_comp  \
0   Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
1           Prima Freshmart, Kalideres      -6.147619      106.702415
2       Domino's Pizza, Citra Garden 2      -6.144993      106.706230
3             Kopi Kenangan, GoWork CP      -6.148143      106.708149
4   Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
5           Prima Freshmart, Kalideres      -6.147619      106.702415
6       Domino's Pizza, Citra Garden 2      -6.144993      106.706230
7             Kopi Kenangan, GoWork CP      -6.148143      106.708149
8   Bakso Jawir (JWR), Ruko Duta Indah      -6.147444      106.702417
9           Prima Freshmart, Kalideres      -6.147619      106.702415
10      Domino's Pizza, Citra Garden 2      -6.144993      106.706230
11            Kopi Kenangan, GoWork CP      -6.148143      106.708149
12                KFC, Daan Mogot Baru      -6.153440      106.713879
13          McDonald's, Mal Daan Mogot      -6.151077      106.714432
14   Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
15                KFC, Daan Mogot Baru      -6.153440      106.713879
16          McDonald's, Mal Daan Mogot      -6.151077      106.714432
17   Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
18                KFC, Daan Mogot Baru      -6.153440      106.713879
19          McDonald's, Mal Daan Mogot      -6.151077      106.714432
20   Chatime, Mall Matahari Daan Mogot      -6.151232      106.714229
21                          Mie 2 Rasa      -7.737617      109.007828
22                  Bu Darmi Ayam Rasa      -7.951460      112.654440

    s213id1_comp  s213id2_comp  s213id3_comp
0         334447        692872       2599936
1         334447        692872       2599936
2         334447        692872       2599936
3         334447        692872       2599936
4         334447        692872       2599936
5         334447        692872       2599936
6         334447        692872       2599936
7         334447        692872       2599936
8         334447        692872       2599936
9         334447        692872       2599936
10        334447        692872       2599936
11        334447        692872       2599936
12        334447        699744       2076672
13        334447        699744       2076672
14        334447        699744       2076672
15        334447        699744       2076672
16        334447        699744       2076672
17        334447        699744       2076672
18        334447        699744       2076672
19        334447        699744       2076672
20        334447        699744       2076672
21        334309        862217       7705984
22        330287        322979       3689600

In [41]:
df_inner.to_excel('results2id11.xlsx')
df_inner2.to_excel('results2id13.xlsx')